name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
     - cron : 30 02 * * *   # 8 am IST every day
     - cron : 00 14 * * *   # 730 am IST Every day
     - cron : 00 06 * * 1-5 # 1130 amIST Monday to Friday

jobs:
  run-postman-tests:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout the code
       uses: actions/checkout@v4.2.2

     - name: Install Nodejs and npm
       uses: actions/setup-node@v3.9.1
       with:
          node-version: '22'
     - name: Install Newman and Html-Extra globally
       run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra
     - name: Run Postman Collection with newman
       run: |
            new run 'Inwarranty-Flow Collection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d TestData.csv \
            -r cli,htmlextra


     

    
